global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: 'remnawave'
    static_configs:
      - targets: ['remnawave:3001']
    metrics_path: /metrics
    basic_auth:
      username: admin
      password: metrics_local_password

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
